import { CompanyProfile, DiverProfile, JobPost } from "@/lib/types";

export const divers: DiverProfile[] = [
  { id: "d1", username: "gareth", fullName: "Gareth Nilsen", headline: "Saturation Welder • 2,800+ hrs • IMCA Certified • Available July 2026", bio: "22 campaigns in North Sea and Gulf. Specialist in hyperbaric wet welding and habitat repair scopes.", satHours: 2860, diveHours: 4200, location: "Aberdeen, UK", availabilityStatus: "available", mobilizationNotice: "Ready in 48h", certifications: ["IMCA Bell Diver", "CSWIP 3.1U", "ADCI"], languages: ["English", "Norwegian"], specialties: ["Wet Welding", "Habitat Construction"], verified: true },
  { id: "d2", username: "elin", fullName: "Elin Strand", headline: "Saturation Diver • NDT Tech • Offshore Wind Specialist", bio: "Focused on offshore wind monopile inspection and defect mapping. 1,900 sat hours.", satHours: 1900, diveHours: 3500, location: "Bergen, NO", availabilityStatus: "deployed", mobilizationNotice: "Available from 10 Aug", certifications: ["IMCA", "PCN NDT"], languages: ["Norwegian", "English"], specialties: ["NDT", "Wind Farm"], verified: true },
  { id: "d3", username: "omar", fullName: "Omar Halabi", headline: "Deep-sea Construction Diver • 2,200 sat hrs", bio: "Pipeline tie-ins, spool installation, and subsea metrology in MENA and Europe.", satHours: 2200, diveHours: 4100, location: "Rotterdam, NL", availabilityStatus: "available", mobilizationNotice: "Ready in 72h", certifications: ["ADCI", "IMCA", "BOSIET"], languages: ["English", "Arabic"], specialties: ["Construction", "Pipelines"], verified: true },
  { id: "d4", username: "johan", fullName: "Johan Persson", headline: "Air/Sat Diver • Offshore Oil & Gas shutdowns", bio: "Experienced in shutdown scopes and emergency leak clamp installation.", satHours: 1600, diveHours: 3900, location: "Gothenburg, SE", availabilityStatus: "available", mobilizationNotice: "Ready in 24h", certifications: ["IMCA", "OGUK Medical"], languages: ["Swedish", "English"], specialties: ["Shutdowns", "Repair"], verified: true },
  { id: "d5", username: "ricardo", fullName: "Ricardo Sousa", headline: "Saturation ROV-Assisted Diver • 1,400 sat hrs", bio: "Bridge between dive and ROV teams for deep intervention and survey support.", satHours: 1400, diveHours: 3000, location: "Lisbon, PT", availabilityStatus: "deployed", mobilizationNotice: "Available 01 Sep", certifications: ["IMCA", "ROV Pilot Intro"], languages: ["Portuguese", "English"], specialties: ["ROV Integration", "Survey"], verified: true },
  { id: "d6", username: "martin", fullName: "Martin Lowe", headline: "Wet Welder • Structural Repair • 2,050 sat hrs", bio: "Hull and jacket steel repair specialist with documented QA/QC traceability.", satHours: 2050, diveHours: 3800, location: "Newcastle, UK", availabilityStatus: "available", mobilizationNotice: "Ready in 5 days", certifications: ["CSWIP 3.1U", "IMCA"], languages: ["English"], specialties: ["Welding", "QA/QC"], verified: true },
  { id: "d7", username: "sami", fullName: "Sami Kareem", headline: "NDT and Inspection Diver • Offshore Asset Integrity", bio: "Long campaign history in ultrasonic and MPI inspections offshore.", satHours: 1750, diveHours: 3400, location: "Doha, QA", availabilityStatus: "available", mobilizationNotice: "Ready in 72h", certifications: ["PCN NDT", "ADCI"], languages: ["English", "Arabic"], specialties: ["NDT", "Integrity"], verified: false },
  { id: "d8", username: "isak", fullName: "Isak Moen", headline: "Offshore Wind Diving Supervisor Pathway", bio: "Diver progressing into supervisory role with strong HSE reporting discipline.", satHours: 1200, diveHours: 2800, location: "Esbjerg, DK", availabilityStatus: "deployed", mobilizationNotice: "Available after current campaign", certifications: ["IMCA", "First Aid Offshore"], languages: ["Danish", "English"], specialties: ["Wind", "HSE"], verified: true },
];

export const companies: CompanyProfile[] = [
  { id: "c1", companyName: "North Arc Subsea", location: "Aberdeen", subscriptionStatus: "active", plan: "249" },
  { id: "c2", companyName: "BlueSpan Offshore", location: "Stavanger", subscriptionStatus: "active", plan: "199" },
  { id: "c3", companyName: "Baltic Marine Works", location: "Gdansk", subscriptionStatus: "past_due", plan: "149" },
];

export const jobs: JobPost[] = [
  { id: "j1", companyId: "c1", title: "Urgent: 2 Sat Welders + 1 NDT Tech", description: "35-day campaign. Hyperbaric weld repair and final inspection package.", location: "Aberdeen", startDate: "2026-06-12", requiredCerts: ["IMCA", "CSWIP 3.1U"], budgetRange: "€1,200-€1,800/day", status: "open" },
  { id: "j2", companyId: "c2", title: "Offshore Wind Inspection Team", description: "Monopile jacket inspection and report package.", location: "North Sea", startDate: "2026-07-04", requiredCerts: ["IMCA", "PCN NDT"], budgetRange: "€900-€1,300/day", status: "open" },
  { id: "j3", companyId: "c3", title: "Pipeline Tie-in Campaign", description: "Deep-sea construction support, 28 days with possible extension.", location: "Baltic Sea", startDate: "2026-08-18", requiredCerts: ["ADCI", "BOSIET"], budgetRange: "€1,000-€1,500/day", status: "open" },
];
